name: Checks for basic working

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:


  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run lint
        run: dotnet format -v diag

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore and build
        run: |
          dotnet restore
          dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
