name: Xunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Restoring and building...
        run: |
          dotnet restore
          dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Testing...
        run: dotnet test --no-build --verbosity normal
